#!/usr/bin/env bash

WORK_PATH=$(dirname $(readlink -f $0))

# Cr/  Mo/  Nb/  Sn/  Ti/  Zr/

for DIFFUSION_ATOM in  Al/ Cr/  Mo/  Nb/  Sn/  Ti/  Zr/ ; do
	echo "DIFFUSION ATOM is" $DIFFUSION_ATOM
	for DIFFUSION_DIR in 41-01/ 41-07/ 57-07/ 57-19/; do
		for DIFFUSION_STEP in 00/ 01/ 02/ 03/ 04/ ; do
				OUTCAR_PATH=$WORK_PATH/$DIFFUSION_ATOM$DIFFUSION_DIR$DIFFUSION_STEP/OUTCAR
				TARGET_PATH=$WORK_PATH/COPY_OUTCAR/$DIFFUSION_ATOM$DIFFUSION_DIR$DIFFUSION_STEP
				mkdir -p $TARGET_PATH
				cp $OUTCAR_PATH $TARGET_PATH
				if [ -f 'CONTCAR' ]
				then
					CONTCAR_PATH=$WORK_PATH/$DIFFUSION_ATOM$DIFFUSION_DIR$DIFFUSION_STEP'CONTCAR'
					cp $CONTCAR_PATH $TARGET_PATH
				else
					POSCAR_PATH=$WORK_PATH/$DIFFUSION_ATOM$DIFFUSION_DIR$DIFFUSION_STEP'POSCAR'
					cp $POSCAR_PATH $TARGET_PATH
				fi
		done
		echo $DIFFUSION_DIR "Done!"
	done
done